From python:3.7.9

ENV PYTHONUNBUFFERED 1

RUN apt-get -y update

RUN apt-get -y install vim 

RUN mkdir /docker-server

ADD . /docker-server 

WORKDIR /docker-server 

RUN pip3 install --upgrade pip 

RUN pip3 install -r requirements.txt 

EXPOSE 8000
CMD ["python", "manage.py","runsslserver","--certificate","django.crt","--key","django.key","0.0.0.0:8000"]