From python:3.7.9

ENV PYTHONUNBUFFERED 1

RUN apt-get -y update

RUN apt-get -y install vim

COPY ./ /home/ubuntu/Django/

WORKDIR /home/ubuntu/Django/


RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py","runsslserver","--certificate","cert.pem","--key","privkey.pem","0.0.0.0:8000"]

